version: "3.7"

services:
  # <service_name>:
  #   build: <path_to_directory_of_dockerfile>
  #   image: <image_name>
  #   volumes:
  #     - <path_to_volume>:<path_to_volume_in_container>
  #   ports:
  #       - <host_port>:<container_port>
  #   depends_on:
  #     - "<other_service>"
  #   restart: on-failure

  nginx:
    build: ./requirements/nginx/
    ports:
      - 80:80 # host:container
      - 443:443
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html
    init: true
    container_name: nginx
    networks:
     - mynet
    depends_on:
      - php


  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db_volume:/var/lib/mysql
    restart: on-failure
    environment:
      - ROOT_PASS=r11tt11r 
    init: true
    container_name: mariadb
    networks:
      - mynet

  php:
    build: ./requirements/php
    volumes:
      - wordpress_data:/var/www/html
    restart: on-failure
    init: true
    container_name: php
    networks:
      - mynet
    depends_on:
      - mariadb

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/login/data/databases

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/login/data/wordpress

networks:
  mynet:
    driver: bridge
